<?php

namespace Gestion\ArticleBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * profilRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class profilRepository extends EntityRepository
{
}
