article_index:
    path:     /
    defaults: { _controller: "ArticleBundle:article:index" }
    methods:  GET

article_show:
    path:     /{id}/show
    defaults: { _controller: "ArticleBundle:article:show" }
    methods:  GET

article_new:
    path:     /new
    defaults: { _controller: "ArticleBundle:article:new" }
    methods:  [GET, POST]

article_edit:
    path:     /{id}/edit
    defaults: { _controller: "ArticleBundle:article:edit" }
    methods:  [GET, POST]

article_delete:
    path:     /{id}/delete
    defaults: { _controller: "ArticleBundle:article:delete" }
    methods:  DELETE
